Develop signin
ErlendLandro/WasteTrader pull request #20
Opened 2017-06-14 11:53 UTC by philipborg

2017-06-14 15:10 UTC, ErlendLandro requested changes
Det ser bra ut. Tror dock det har kommit med några buggar, när jag går till /hitta efter att ha loggat in så får jag detta:

```
GET http://localhost:8080/Waste2Value/Hitta

System.Exception: ScErrDataBindingForJsonException (SCERR14012): An exception occurred when a databinding for a property in json was used. Property 'UserName' in 'MasterPage.FindPage.SellWaste.SellWasteJson'.
Version: 2.3.1.6542.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR14012.
   at lambda_method(Closure , Json )
   at Starcounter.Templates.Property`1.CheckAndSetBoundValue(Json parent, Boolean addToChangeLog) in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 214
   at Starcounter.Json.SetBoundValuesInTuple() in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 432
   at Starcounter.Json.RetriableSetBoundValues(Boolean retryOnError) in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 405
   at Starcounter.Json.<>c__DisplayClass128_0.<ScopeAndSetBoundValuesInTuple>b__0() in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 378
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 67
   at Starcounter.Templates.TObjArr.CheckAndSetBoundValue(Json parent, Boolean addToChangeLog) in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.XSON\Templates\TObjArr.cs:line 162
   at Starcounter.Json.SetBoundValuesInTuple() in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 432
   at Starcounter.Json.RetriableSetBoundValues(Boolean retryOnError) in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 399
   at Starcounter.Json.<>c__DisplayClass128_0.<ScopeAndSetBoundValuesInTuple>b__0() in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 378
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 67
   at Starcounter.Templates.TObject.CheckAndSetBoundValue(Json parent, Boolean addToChangeLog) in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.XSON\Templates\TObject.cs:line 116
   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 341
   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 242
   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 217
   at Starcounter.Json.<>c__DisplayClass123_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 198
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 67
   at Starcounter.XSON.ChangeLog.Generate(Boolean flushLog, Change[]& changeArr) in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\ChangeLog.cs:line 100
   at Starcounter.XSON.JsonPatch.Generate(Json json, Boolean flushLog, Boolean includeNamespace) in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 117
   at Starcounter.Internal.JsonMimeConverter.Convert(Request request, IResource before, MimeType mimeType, MimeType& resultingMimeType) in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\JsonMimeConverter.cs:line 18
   at Starcounter.Json.AsMimeType(MimeType mimeType, MimeType& resultingMimeType, Request request) in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.XSON\Class Json\Json.IResource.cs:line 45
   at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.Internal\Http\Response.cs:line 809
   at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.Internal\Http\Request.cs:line 1241
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-5682\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 810
Data {
IsRethrown=True
}
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR14012
---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Simplified.Ring1.Something.get_Name()
   at WasteTrader.Database.Waste.get_UserName() in C:\Users\Mackiovello\Documents\GitHub\WasteTraderMaterial\src\WasteTrader\Database\Waste.cs:line 39
   at lambda_method(Closure , Json )
HResult=-2147467261
```

2017-06-14 15:10 UTC, ErlendLandro commented on src/WasteTrader/Database/Waste.cs
> +        public string UserName => User.Name;
These should be moved to a separate class that inherits from `SystemUser`. This class gets too fat if it also should contain information about the "owner" of the waste.

2017-06-14 15:10 UTC, ErlendLandro commented on src/WasteTrader/ViewModels/UserPage.json.cs
> +        public string Html => "/WasteTrader/views/UserPage.html";
Why is the Html set here instead of in the JSON file? Why are `BuyWastes` and `SellWastes` always null? Wouldn't that mean that the view-model is never set?

2017-06-14 17:02 UTC, philipborg commented on src/WasteTrader/ViewModels/UserPage.json.cs
> +        public string Html => "/WasteTrader/views/UserPage.html";
Fixat bland annat detta i en ny branch där jag flyttat runt en hel del. Borde kanske flyttat runt allt i denna branchen istället.

2017-06-16 14:00 UTC, philipborg commented
New review request @Mackiovello

2017-06-16 15:49 UTC, merged